#ifndef PIPELINE_H
#define PIPELINE_H

#include <stdint.h>
#include <stdbool.h>

/* Control signals generated by the control unit in ID */
typedef struct {
    bool    reg_dst;    /* 0→rt dest, 1→rd dest              */
    bool    alu_src;    /* 0→register, 1→sign-extended imm   */
    bool    mem_to_reg; /* 0→ALU result, 1→memory read data  */
    bool    reg_write;
    bool    mem_read;
    bool    mem_write;
    bool    branch;
    bool    branch_ne;  /* 1→BNE, 0→BEQ                      */
    bool    jump;
    bool    jal;
    bool    jr;
    uint8_t alu_op;     /* 0=AND,1=OR,2=ADD,6=SUB,7=SLT,3=funct */
    bool    halt;
    bool    syscall;
} Ctrl;

/* ── Pipeline registers ───────────────────────────────── */

typedef struct {
    uint32_t instr;
    uint32_t pc4;       /* word index of next instruction     */
    uint32_t pc_plus_4;
    bool     valid;
    char     mnem[24];
} IFID;

typedef struct {
    uint32_t pc4;
    uint32_t pc_plus_4;
    uint32_t instr;
    int32_t  rs_val, rt_val;
    int16_t  imm;
    uint8_t  rs, rt, rd, funct, shamt;
    Ctrl     ctrl;
    bool     valid;
    char     mnem[24];
} IDEX;

typedef struct {
    int32_t  alu_result;
    uint32_t pc_plus_4;
    int32_t  rt_val;    /* for SW                             */
    uint32_t branch_tgt;
    int32_t  write_data;
    uint8_t  dest;      /* write-back destination register    */
    bool     zero;
    Ctrl     ctrl;
    bool     valid;
    char     mnem[24];
} EXMEM;

typedef struct {
    int32_t  mem_data;
    int32_t  alu_result;
    uint32_t pc_plus_4;
    uint8_t  dest;
    Ctrl     ctrl;
    bool     valid;
    char     mnem[24];
} MEMWB;

/* ── Full pipeline state ──────────────────────────────── */
typedef struct {
    IFID  if_id;
    IDEX  id_ex;
    EXMEM ex_mem;
    MEMWB mem_wb;

    /* Diagnostic flags reset each cycle (used by viz) */
    bool  stall;
    bool  data_hazard;
    bool  branch_flush;

    /* Last instruction that completed WB (for viz) */
    char  wb_mnem[24];
    bool  wb_valid;
    uint8_t wb_reg;
    int32_t wb_val;
} Pipeline;

void pipeline_init(Pipeline *p);

#endif /* PIPELINE_H */
